version: 2

sources:
  - name: raw
    schema: dbt_sales
    tables:
      - name: raw_orders
        description: "Tabela bruta de pedidos contendo informações de vendas"
        columns:
          - name: order_id
            description: "ID único do pedido"
            tests:
              - unique
              - not_null
          - name: customer_id
            description: "ID do cliente que fez o pedido"
          - name: order_date
            description: "Data em que o pedido foi realizado"
          - name: product_id
            description: "ID do produto vendido"
          - name: quantity
            description: "Quantidade de itens vendidos"
          - name: unit_price
            description: "Preço unitário do produto"
          - name: total_amount
            description: "Valor total do pedido (quantidade * preço unitário)"
